services:
  evently.api:
    image: ${DOCKER_REGISTRY-}eventlyapi
    build:
      context: .
      dockerfile: src/API/Evently.Api/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081 
  
  evently.seq:
    image: datalust/seq:latest
    container_name: Evently.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341 
      - 8081:80